### ISSUE TITLE
Link to online version

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/pokelist-quiz-4ahif-JonasReichhardt#1]
https://cdn.rawgit.com/rstropek-teaching/pokelist-quiz-4ahif-JonasReichhardt/6e2d5be8/index.html

**Comment by rstropek** [comment]
@JonasReichhardt Thank you for your homework. I tested your app and it worked well 👍 .

Greetings,
Rainer Stropek.
